language: node_js
sudo: true
node_js: stable
before_install:
- sudo apt-get install expect
install:
- cd example && npm install --no-package-lock && ./initialize
script:
- cd test-project && npm install && npm run build
notifications:
  email: false
